### PR TITLE
API access implemented for all structs derived from ZTSceneryType

### PR DESCRIPTION
**Pull request by GoosiferIO**
# Overview

Added support for ZTSceneryType API access. The following new properties have been added to the ZTSceneryType struct:

- `purchase_cost`
- `name_id`
- `help_id`
- `habitat`
- `location`
- `era`
- `max_food_units`
- `stink`
- `esthetic_weight`
- `selectable`
- `deletable`
- `foliage`
- `auto_rotate`
- `land`
- `swims`
- `underwater`
- `surface`
- `submerge`
- `only_swims`
- `needs_confirm`
- `gawk_only_from_front`
- `dead_on_land`
- `dead_on_flat_water`
- `dead_underwater`
- `uses_tree_rubble`
- `forces_scenery_rubble`
- `blocks_los`

Functions added:

- `get_info_image_name` - returns the name of the info image for the scenery type
- `set_config` - allows setting the configuration of the scenery type from the console
- `print_config` - prints the configuration of the scenery type config to the console

# Usage

## Console Commands

The `selected_scenery` command can be used to access the ZTSceneryType API. The following commands are supported:

- `selected_scenery` - returns the details of the selected scenery type
- `selected_scenery -v` - returns the configuration of the selected scenery type
- `selected_scenery -<config> <value>` - sets the configuration of the selected scenery type. The `<config>` argument needs to be exactly as defined in the proper configuration files (i.e. `cPurchaseCost`, `cNameID`, etc.)

Example: `selected_scenery -cPurchaseCost 1000` - sets the purchase cost of the selected scenery type to 1000`

## Backend API

```Rust
// get the selected entity type
let entity_type_address = get_selected_entity_type(); // grab the address of the selected entity type
let scenery_type = ZTSceneryType::new(entity_type_address).unwrap(); // create a copied instance of the entity type

// scenery type operations
let log_purchase = scenery_type.set_config("-cPurchaseCost", "1000"); // set the purchase cost of the selected scenery type to 1000 with logging
let dir_purchase = scenery_type.purchase_cost = 1000; // set the purchase cost of the selected scenery type to 1000 without logging
println(scenery_type.purchase_cost); // prints the purchase cost of the selected scenery type

// access bfentitytype properties
let ncolors = scenery_type.bfentitytype.ncolors;
// do something with ncolors
```

# Considerations

In a future update will make this a little smarter so that separate `selected_type` and `selected_scenery` commands aren't necessary. For now will need to be familiar with inheritance rules between the types to know who has access to which properties.

### CODE REVIEW

**Comment by GoosiferIO** [comment]
# Overview

Added support for the ZTBuildingType API. Includes the following new properties:

```Rust 
struct ZTBuildingType {
    ztscenerytype: ZTSceneryType, // 0x000
    i_capacity: i32, // 0x16C
    toy_satisfaction: i32, // 0x170
    time_inside: i32, // 0x174
    default_cost: f32, // 0x178
    low_cost: f32, // 0x17C
    med_cost: f32, // 0x180
    high_cost: f32, // 0x184
    price_factor: f32, // 0x188 
    upkeep: f32, // 0x18C
    pad1: [u8; 0x194 - 0x190], // -- padding: 
    hide_user: bool, // 0x194
    set_letter_facing: bool, // 0x195
    draw_user: bool, // 0x196
    hide_cost_change: bool, // 0x197
    hide_commerce_info: bool, // 0x198
    hide_regular_info: bool, // 0x199
    holds_onto_user: bool, // 0x19A
    user_tracker: bool, // 0x19B
    idler: bool, // 0x19C
    exhibit_viewer: bool, // 0x19D
    pad2: [u8; 0x1A0 - 0x19E], // -- padding: 2 bytes
    alternate_panel_title: u32, // 0x1A0
    direct_entrance: bool, // 0x1A4
    hide_building: bool, // 0x1A5
    user_stays_outside: bool, // 0x1A6
    user_teleports_inside: bool, // 0x1A7
    user_uses_exit: bool, // 0x1A8
    user_uses_entrance_as_emergency_exit: bool, // 0x1A9
    pad3: [u8; 0x1B8 - 0x1AA], // -- padding: 9 bytes
    adult_change: i32, // 0x1B8
    child_change: i32, // 0x1BC
    hunger_change: i32, // 0x1C0
    thirst_change: i32, // 0x1C4
    bathroom_change: i32, // 0x1C8
    energy_change: i32, // 0x1CC
}
```

# Console Commands

## `selected_building`

### No Arguments

- Returns the selected building type and other details

```Rust
selected_building
```

### `[-v]`

- Returns printed configuration of the selected building type from memory

```Rust
selected_building [-v]
```

### `[-<config> <value>]`

- Sets the configuration of the selected building type

```Rust
selected_building [-<config> <value>]
```

# Backend API

## Usage 

```Rust
let building_type = ZTBuildingType::new(address).unwrap();

// with logging
let set_capacity = building_type.set_config("-cCapacity", "100"); // sets the capacity of the building type to 100
if set_capacity.is_ok() {
    info!("{}", set_capacity.unwrap());
}
else {
    error!("{}", set_capacity.unwrap());
}

// direct operation without logging
let set_capacity = building_type.i_capacity = 100;

// direct read operation
println("Capacity: {}", building_type.i_capacity);
```

# Considerations

Missing hooks for `[Characteristics/Strings]`, `[UseSound]`, `[Sells]`, `[EstheticBonus]`, `[Satisfies]`, `[Slots]`, `[Member]`, `[Member]` sections. Most of `[Characteristics/Integers]` are implemented in this version.

**Comment by GoosiferIO** [comment]
# Overview

Added support for the ZTFenceType API. Includes the following new properties:

- `strength`
- `life`
- `decayed_life`
- `decayed_delta`
- `break_sound_atten`
- `open_sound_atten`
- `see_through`
- `is_jumpable`
- `is_climbable`
- `indestructible`
- `is_electrified`
- `no_draw_water`

# Refactored Console Commands 

Previously, each struct had its own command denoted as `selected_type`, `selected_scenery`, and `selected_building`, but this was redunandant. Now, we just need `sel_type` to select the entity type. The console will know what type, what configuration to print, and what API to make available to avoid crashes.

Usage is the same as before:

- `sel_type` to print just details about the entity type
- `sel_type -v` to print the configuration of the entity type
- `sel_type -<config> <value>` to set a configuration option

## New Console Commands

`make_sel <cName_id>` - makes the entity type with the specified name ID selectable on the map. This is useful to then select things like fences, foliage, etc and run `sel_type` operations.

# Backend Changes

Add the following functions to `ztworldmgr.rs`

- Added `determine_entity_type` function to determine the entity type of the selected entity type
- Added `get_entity_type_by_id` function to get the entity type by its ID

**Comment by GoosiferIO** [comment]
# Overview

Adds support for the `ZTFoodType` API. Includes the following new properties:

- `keeper_food_type`

No other changes.

**Comment by GoosiferIO** [comment]
# Overview

Added support for ZTTankeFilterType API access. This includes the following properties:

- `starting_health` (int)
- `decayed_health` (int)
- `decay_time` (int)
- `filter_delay` (int)
- `filter_upkeep` (int)
- `filter_clean_amount` (int)
- `filter_decayed_clean_amount` (int)
- `healthy_atten` (int)
- `decayed_atten` (int)

The following methods have been added to the ZTTankFilterType struct:

- `get_healthy_sound` (returns a string)
- `get_decayed_sound` (returns a string)

# Console

Prints the configuration specific to the ZTTankFilterType struct. See usage examples above for more information.

**Comment by GoosiferIO** [comment]
# Overview 

Added support for ZTTankWallType API access. This includes the following properties:

- `portal_open_sound_atten` (int)
- `portal_close_sound_atten` (int)

The following functions were added to the `ZTTankWallType` struct:

- `get_portal_open_sound(&self) -> String`
- `get_portal_close_sound(&self) -> String`

# Console 

Prints the configuration specific to the ZTTankFilterType struct. See usage examples above for more information.

**Comment by GoosiferIO** [comment]
# Overview

Added API access to ZTPathType. Only one property is available for ZTPathType:

- `material` (u32)

# Considerations

- The `Shapes` structure is missing from paths. Could not find it in the game's memory.

**Comment by GoosiferIO** [comment]
# Overview

Added API access to `ZTRubbleType`.

## Properties

- `explosion_sound_atten`: i32

## Functions

- `new(address: u32)`
- `get_explosion_sound(&self) -> String`
- `set_config(&mut self, config: &str, value: &str) -> Result<String, &'static str>`
- `print_config_integers(&self) -> String`

## Addendums

Previous comments forgot to mention that for every API implemented, each one includes an implementation of the following functions:

- `new(address: u32) -> Option<&'static mut Self>`: This function creates a new instance of the API object and returns it as a mutable reference. If the address is invalid, it returns `None`. This allows operations on the object.
- `set_config(&mut self, config: &str, value: &str) -> Result<String, &'static str>`: This function sets the configuration of the object based on the configuration option and value provided. If the configuration option is invalid, it returns an error message.
- `print_config_integers(&self) -> String`: This function prints the `[Configuration/Integers]` section of the object.

**Review by finnhartshorn — APPROVED** [review]

**Pull request merged**
