### PR TITLE
Feature: Combined mods

### PR DESCRIPTION
**Pull request by finnhartshorn**
## Description
Load both OpenZT data and Zoo Tycoon Data from each .ztd, based on `ztd_type` in `meta.toml`

## Proposed Changes
- Addresses https://github.com/openztcc/openzt/issues/44
- Adds lazy loading of resources rather than loading all resources on start (to be expanded in https://github.com/openztcc/openzt/issues/51)

## Checklist
 - [x] Docs https://github.com/GoosiferIO/ZooBerry-Docs/pull/2
 - [x] Manually tested
 - [ ] Unit tests (where possible)

### CODE REVIEW

**Comment by GoosiferIO** [comment]
I think instead we can have a `legacy` flag in the meta.toml. If it exists, new mod. If not, we scan the mod directory the old way. We could of course just scan the directory for a pattern like you said but I think it would solve so many steps in our other systems, specifically considering PANDA.

**Comment by GoosiferIO** [comment]
Or sorry I meant, if `legacy` is false == new mod.

**Comment by finnhartshorn** [comment]
> I think instead we can have a `legacy` flag in the meta.toml. If it exists, new mod. If not, we scan the mod directory the old way. We could of course just scan the directory for a pattern like you said but I think it would solve so many steps in our other systems, specifically considering PANDA.

The main motivation is being able to add in OpenZT stuff to existing mods and have new features work seamlessly if OpenZT is installed. Feels annoying to need to have a separate mod to add a custom habitat or location to an animal.

Also just one less flag that could be in the wrong state.

The only reason I need to change anything to start with is because my first implementation is very naive, I just load any file inside a `.ztd`, whereas Zoo Tycoon looks for `.cfg` files or `.uca/ucs/ucb` files and reads their contents to figure out what resources to load.

**Comment by finnhartshorn** [comment]
> specifically considering PANDA.

Sorry, missed this part. Maybe we should have a `mod_type` enum which defaults to `openzt` but can also be `legacy` or `combined`. I really want to support combined mods, but agree we don't want to have to implement complex detection logic in both OpenZT and PANDA

**Comment by GoosiferIO** [comment]
Yeah initially I figured just the presence of a toml file in the root folder would be enough but it would be nice to generate toml files even for legacy files, so I agree some kind of flag would be necessary. I'd be happy with an enum flag, but maybe a different name for clarity. Mod type could also mean the kind of thing it's modifying: textures, new buildings, etc. I can't think of something better off the top of my head though. `mod_status` maybe? I'm not sure.

**Comment by finnhartshorn** [comment]
> Yeah initially I figured just the presence of a toml file in the root folder would be enough but it would be nice to generate toml files even for legacy files, so I agree some kind of flag would be necessary. I'd be happy with an enum flag, but maybe a different name for clarity. Mod type could also mean the kind of thing it's modifying: textures, new buildings, etc. I can't think of something better off the top of my head though. `mod_status` maybe? I'm not sure.

Maybe `ztd_type`?

**Comment by GoosiferIO** [comment]
Yeah that's perfect

**Pull request merged**
